
[tool.black]
line-length = 120

[tool.isort]
profile="black"
line_length=1
multi_line_output=3

[tool.pylint]
max-line-length = 120
max-args = 6
good-names=["i", "j", "k", "df"]

# C0103 - var snake_case warn
# C0114 - missing-module-docstring
# C0115 - missing-class-docstring
# C0116 - missing-function-docstring
# W0718 - broad-exception-caught
# W0719 - broad-exception-raised
# R0903 - too-few-public-methods
# W0511 - fixme
disable=["C0103", "C0114", "C0115", "C0116", "W0718", "W0719", "R0903", "W0511"]

[tool.mypy]

# ignore_missing_imports = "True"
